class_name Enums

enum FALLING_PIECE_TYPE {
	UNINITIALIZED = -1,
	EYE_OF_NEWT = 0,
	GIANTS_THUMB = 1,
	VAMPIRES_TEETH = 2,
	WING_OF_BAT = 3,
	POT_BOTTOM = 4,
	POT_TOP = 5
}

# TODO: Remove and replace with LANDING_ACTION_RESULT
enum FALLING_PIECE_LANDING_TYPE {
	UNRECOGNIZED = -1,
	GROUNDED = 0,
	CLEARED = 1,
}

enum FALLING_PIECE_UPDATE_TYPE {
	UNRECOGNIZED = -1,
	CLEARED = 0,
	MOVE_INTO_POT_FINISHED = 1,
	DATA_RESET = 2,
	FAIL_COMPLETE = 3
}

enum LANDING_ACTION_TYPE {
	UNINITIALIZED = -1,
	# Default Behavior:
	MATCH_CLEAR = 0,
	# Pot Top:
	TO_POT_AND_POT_CLEAR = 1,
	# Spoon:
	TO_POT_CLEAR = 2,
}

enum LANDING_ACTION_RESULT {
	GROUNDED = 0,
	CLEAR_MATCHED = 1,
	CLEAR_SELF_ONLY = 2,
	CLEAR_POT_AND_ABOVE = 3,
	CLEAR_ABOVE_POT_ONLY = 4,
}

enum ON_REMOVED_RESULT {
	SUCCESS = 0,
	NO_EFFECT = 1,
	NEGATIVE_EFFECT = 2,
}
