class_name Enums

enum FALLING_PIECE_TYPE {
	UNINITIALIZED = -1,
	EYE_OF_NEWT = 0,
	GIANTS_THUMB = 1,
	VAMPIRES_TEETH = 2,
	WING_OF_BAT = 3
}

enum FALLING_PIECE_LANDING_TYPE {
	UNRECOGNIZED = -1,
	GROUNDED = 0,
	CLEARED = 1,
}
